[package]
name = "virtualmetric-winrust"
version = "0.1.0"
authors = ["Yusuf-Papurcu"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wmi = "0.6"
serde_json = "1.0"
tiny_http = "0.6"
serde = "*"
clap = "*"